# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField()),
                ('media_version', models.CharField(max_length=200)),
                ('media_country', models.CharField(choices=[(b'FR', b'France'), (b'UK', b'United Kingdom'), (b'US', b'United States')], max_length=2)),
                ('media_nb_view', models.IntegerField()),
                ('release_date_last_view', models.DateField()),
                ('media_nb_tags', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='media_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_category_id', models.IntegerField()),
                ('media_category_name', models.CharField(choices=[(b'MV', b'musicvideo'), (b'T', b'trailer'), (b'PER', b'personal'), (b'M', b'movie'), (b'D', b'documentary'), (b'A', b'anime'), (b'PUB', b'publicity')], max_length=3)),
                ('media_category_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='media_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_info_id', models.IntegerField()),
                ('media_info_source', models.CharField(choices=[(b'LOC', b'local'), (b'YT', b'youtube'), (b'VIM', b'vimeo')], max_length=3)),
                ('media_info_address', models.CharField(max_length=200)),
                ('media_info_thumbnail_adress', models.CharField(max_length=200)),
                ('media_info_name', models.CharField(max_length=200)),
                ('media_info_urlbar', models.CharField(max_length=200)),
                ('media_info_artist_name', models.CharField(max_length=200)),
                ('media_info_director_name', models.CharField(max_length=200)),
                ('media_info_production_company', models.CharField(max_length=200)),
                ('media_info_date_release', models.DateField()),
                ('media_info_cert_source', models.CharField(choices=[(b'IVM', b'imvdb'), (b'DM', b'dailymotion')], max_length=3)),
                ('media_info_cert_id', models.IntegerField()),
                ('media_info_certified', models.BooleanField(default=False)),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orange.media')),
            ],
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pls_id', models.IntegerField()),
                ('pls_user_id', models.IntegerField()),
                ('pls_name', models.CharField(max_length=200)),
                ('pls_description', models.CharField(max_length=200)),
                ('pls_duration', models.IntegerField()),
                ('pls_nb_view', models.IntegerField()),
                ('pls_date_last_view', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='tj_media_playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tj_media_pls_id', models.IntegerField()),
                ('tj_media_channel_position', models.IntegerField()),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orange.media')),
                ('pls_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orange.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='tj_user_media_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tj_user_media_info_id', models.IntegerField()),
                ('tj_media_date_dbinsert', models.DateField()),
                ('media_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orange.media_info')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_mail', models.CharField(max_length=200)),
                ('user_login', models.CharField(max_length=200)),
                ('user_pwd', models.CharField(max_length=200)),
                ('user_firstname', models.CharField(max_length=200)),
                ('user_lastname', models.CharField(max_length=200)),
                ('user_age', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='tj_user_media_info',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orange.user'),
        ),
        migrations.AddField(
            model_name='media',
            name='media_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orange.media_category'),
        ),
    ]
