# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='pls_date_last_view',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='pls_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='pls_nb_view',
            field=models.IntegerField(null=True),
        ),
    ]


