# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 08:37
from __future__ import unicode_literals

from django.db import migrations, models

def create_playlists(apps, schema_editor):
    playlist = apps.get_model("orange", "playlist")
    playlist_rock = playlist()
    playlist_rock.pls_id = 1
    playlist_rock.pls_user_id = 1
    playlist_rock.pls_name = "rock"
    playlist_rock.pls_description = "For those who like powerful music"
    #playlist_rock.pls_duration = ""
    #playlist_rock.pls_nb_view = 0
    #playlist_rock.pls_date_last_view = ""
    playlist_rock.save()

    playlist_pop = playlist()
    playlist_pop.pls_id = 2
    playlist_pop.pls_user_id = 1
    playlist_pop.pls_name = "pop"
    playlist_pop.pls_description = "For those who like popular music"
    #playlist_pop.pls_duration = ""
    #playlist_pop.pls_nb_view = 0
    #playlist_pop.pls_date_last_view = ""
    playlist_pop.save()



class Migration(migrations.Migration):
    dependencies = [
        ('orange', '0002_auto_20160126_0937'),
    ]


    operations = [
        migrations.RunPython(create_playlists),
    ]
